### ISSUE TITLE
Add token name as response

### ISSUE THREAD

**Issue by Eeysirhc** [abchrisxyz/ergowatch#16]
**Request URL:** https://ergo.watch/api/v0/tokens/{token_id}/supply

**Response:**
{
  "name:" {token_name},
  "total": 0,
  "circulating": 0,
  "burned": 0
}

**Comment by abchrisxyz** [comment]
@Eeysirhc, if we add a `tokens/{token_id}/details` API providing:

```
{
	name: ...
	description: ...
	emitted: ...
	decimals: ...
}
```

Would you still need the token name in the supply response?

**Comment by Eeysirhc** [comment]
@abchrisxyz i think your proposed solution is a better approach instead of rewriting the /supply endpoint

long answer short: yes please and thank you!

**Comment by abchrisxyz** [comment]
Added `tokens/{token_id}` returning
```
{
  "token_id": "string",
  "emission_amount": 0,
  "name": "string",
  "description": "string",
  "decimals": 0,
  "standard": "string"
}
```

**Comment by Eeysirhc** [comment]
thank you! will patiently wait for the next release :)

**Comment by Eeysirhc** [comment]
Implemented on my side - thank you !
