### ISSUE TITLE
Add locked and/or contract token supply

### ISSUE THREAD

**Issue by Eeysirhc** [abchrisxyz/ergowatch#19]
**Request URL:** https://ergo.watch/api/v0/tokens/{token_id}/supply

**Response**
{
"total": 0,
"circulating": 0,
"burned": 0,
"locked/contract": 0
}

**Motivation:** when retrieving token supply data, need a solution to separate "circulating" supply from tokens that are "locked in smart contracts." Since these tokens are not actually in circulation I propose adding a new response to the endpoint to identify non-P2PK addresses.

Using [ErgoPad data](https://docs.google.com/spreadsheets/d/1uvFKCo8jd28CT41hOoYBeX1iBkZ_7zQPUXQKt44dtQo/edit?usp=sharing) as an example:
- Staking contract
- Vesting contract
- ErgoDEX liquidity pools

**Comment by abchrisxyz** [comment]
Agreed. Been planning to add `p2pk/supply` and `contracts/supply` once the backend supports it. Just like `p2pk/count` and `contracts/count`, they'd have a `token_id` query parameter. Potentially `bal_ge`/`bal_lt` as well.

Having it split across P2PK and contracts in `tokens/supply` could be handy as well indeed.

**Comment by abchrisxyz** [comment]
Ended up doing this:
```
{
  "emitted": 100,
  "in_p2pks": 30,
  "in_contracts": 50,
  "burned": 20
}
```
Makes it somewhat clearer what can be summed together
